[package]
name = "templat-projektarbeit"
version = "0.1.17"
entrypoint = "Template_P/lib.typ"
categories = [ ]
disciplines = [ ]
compiler = "0.15.0"
description = "Template für Projektarbeiten an der DHBW"

[template]
path = "Template"
entrypoint = "main.typ"
thumbnail = ""
